export const FETCH_EMAIL_TYPES = 'FETCH_EMAIL_TYPES';
export const FETCH_EMAIL_TYPES_STR = FETCH_EMAIL_TYPES;
export const FETCH_EMAIL_TYPES_SUCCESS = 'FETCH_EMAIL_TYPES_SUCCESS';
export const FETCH_EMAIL_TYPES_SUCCESS_STR = FETCH_EMAIL_TYPES_SUCCESS;
export const FETCH_EMAIL_TYPES_FAILED = 'FETCH_EMAIL_TYPES_FAILED';
export const FETCH_EMAIL_TYPES_FAILED_STR = FETCH_EMAIL_TYPES_FAILED;

export type FETCH_EMAIL_TYPES = typeof FETCH_EMAIL_TYPES;
export type FETCH_EMAIL_TYPES_SUCCESS = typeof FETCH_EMAIL_TYPES_SUCCESS;
export type FETCH_EMAIL_TYPES_FAILED = typeof FETCH_EMAIL_TYPES_FAILED;

export const SHOW_EMAIL_DETAILS = 'SHOW_EMAIL_DETAILS';
export const SHOW_EMAIL_DETAILS_STR = 'SHOW_EMAIL_DETAILS';
export type SHOW_EMAIL_DETAILS = typeof SHOW_EMAIL_DETAILS;